### ISSUE TITLE
Lighthouse (or any other CL) doesn't see any peers

### ISSUE THREAD

**Issue by 1doce8** [gnosischain/lighthouse-client#1]
Hey, 

I faced an issue with setup the Nethermind + Lighthouse using your docker-compose.yml. 
The consensus layer didn't see any peers. I tried to use different clients (Lighthouse, Teku, Prysm) provided by your team. And all these clients didn't see any peers. (Meanwhile, it seems like Nethermind works well, but it stops syncing at some moment without CL)

**Comment by dapplion** [comment]
@1doce8 Current images point to the now deprecated set of bootnodes. Images will be updated shortly
